"""
Create Word, Excel and PowerPoint files — the editable formats `create_pdf`
cannot produce.

**One tool, not three.** Every tool schema is sent to the model on every request,
and for an admin the tool payload is already ~4,400 tokens of an 8192-token
context window. Three separate tools would cost ~435 tokens per turn forever;
one with a `format` parameter costs ~150. On a 7B local model that difference is
real working room, not bookkeeping.

**Everything written here is marked as AI-generated, twice.** EU AI Act Art 50(2)
asks for machine-readable marking of synthetic output, and `docs/eu-ai-act.md`
claims SUNI does this wherever content leaves the system — previously that meant
PDFs and outgoing email. These are three new exits, so each gets the same
treatment as `pdf_tool`: metadata in the file's own properties (machine-readable)
and a visible line in the document (human-readable). A new output format that
skipped it would quietly turn a documented claim into a false one.
"""
from __future__ import annotations

import asyncio
import csv
import io
import re
from pathlib import Path

from .safe_path import resolve_output_path, safe_output_path

# Same filename rules as pdf_tool — these land on the same filesystem.
_WIN_INVALID = re.compile(r'[<>:"/\\|?*\x00-\x1f]')

_AI_NOTE = "AI-generated by SUNI"
_AI_CREATOR = "SUNI (AI assistant) — artificially generated"
_AI_KEYWORDS = "AI-generated, artificially-generated, SUNI, EU-AI-Act-Art-50"

_FORMATS = ("docx", "xlsx", "pptx")

SCHEMA = {
    "name": "create_document",
    "description": (
        "Create an editable Word (docx), Excel (xlsx) or PowerPoint (pptx) file. "
        "Use when the user wants a document they can edit or a spreadsheet — "
        "use create_pdf instead when they want a fixed, final document. "
        "For xlsx, pass rows as a markdown table or CSV lines."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "content": {"type": "string",
                        "description": "Body text. Markdown headings and bullets are "
                                       "honoured; for xlsx, a markdown table or CSV."},
            "path":    {"type": "string", "description": "Full file path"},
            "format":  {"type": "string", "enum": list(_FORMATS),
                        "description": "docx, xlsx or pptx"},
            "title":   {"type": "string", "description": "Optional document title"},
        },
        "required": ["content", "path", "format"],
    },
}


def _clean(text: str) -> str:
    """Strip markdown emphasis so it does not appear literally in Office files."""
    t = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
    t = re.sub(r'\*{1,2}([^*\n]+)\*{1,2}', r'\1', t)
    t = re.sub(r'`([^`]+)`', r'\1', t)
    return t.strip()


def _heading_level(line: str) -> int:
    m = re.match(r'^(#{1,6})\s+\S', line)
    return len(m.group(1)) if m else 0


def _is_bullet(line: str) -> bool:
    return bool(re.match(r'^\s*[-*•]\s+', line))


# ── rows for a spreadsheet ───────────────────────────────────────────────────
def _parse_rows(content: str) -> list[list[str]]:
    """Accept a markdown table or delimited text; return rows of cells.

    Markdown is tried first because a model asked for "a table" tends to produce
    one, and a pipe table fed to the CSV reader would come back as a single
    column of pipe-laden strings — a spreadsheet that looks generated but cannot
    be sorted or summed.
    """
    lines = [l for l in content.splitlines() if l.strip()]
    if not lines:
        return []

    pipe_rows = [l for l in lines if l.strip().startswith("|") or l.count("|") >= 2]
    if len(pipe_rows) >= 2:
        rows = []
        for line in pipe_rows:
            # a |---|---| separator row carries no data
            if re.match(r'^\s*\|?[\s:\-|]+\|?\s*$', line):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            rows.append([_clean(c) for c in cells])
        if rows:
            return rows

    sample = "\n".join(lines[:5])
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
        delim = dialect.delimiter
    except csv.Error:
        delim = "\t" if "\t" in sample else ","
    return [[c.strip() for c in row]
            for row in csv.reader(io.StringIO("\n".join(lines)), delimiter=delim)
            if row]


# ── writers ──────────────────────────────────────────────────────────────────
def _write_docx(content: str, path: str, title: str) -> None:
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    core = doc.core_properties
    core.author = _AI_CREATOR
    core.comments = _AI_NOTE
    core.keywords = _AI_KEYWORDS
    core.category = "AI-generated document"

    if title:
        doc.add_heading(_clean(title), level=0)

    for raw in content.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue
        if title and line.strip() == title.strip():
            continue
        level = _heading_level(line)
        if level:
            doc.add_heading(_clean(re.sub(r'^#{1,6}\s+', '', line)), level=min(level, 4))
        elif _is_bullet(line):
            doc.add_paragraph(_clean(re.sub(r'^\s*[-*•]\s+', '', line)),
                              style="List Bullet")
        elif re.match(r'^\s*\d+[.)]\s+\S', line):
            doc.add_paragraph(_clean(re.sub(r'^\s*\d+[.)]\s+', '', line)),
                              style="List Number")
        else:
            doc.add_paragraph(_clean(line))

    # Visible disclosure, in the footer of every page.
    footer = doc.sections[0].footer.paragraphs[0]
    footer.text = _AI_NOTE
    for run in footer.runs:
        run.font.size = Pt(8)

    doc.save(path)


def _write_xlsx(content: str, path: str, title: str) -> None:
    from openpyxl import Workbook
    from openpyxl.styles import Font

    rows = _parse_rows(content)
    wb = Workbook()
    ws = wb.active
    ws.title = (_clean(title) or "Sheet1")[:31] or "Sheet1"

    for row in rows:
        ws.append(row)
    if rows:
        for cell in ws[1]:
            cell.font = Font(bold=True)
        # Width from the longest cell, capped so one long note does not make a
        # column unreadable.
        for i, _ in enumerate(rows[0], start=1):
            longest = max((len(str(r[i - 1])) for r in rows if len(r) >= i), default=8)
            ws.column_dimensions[ws.cell(row=1, column=i).column_letter].width = \
                min(max(longest + 2, 8), 60)

    wb.properties.creator = _AI_CREATOR
    wb.properties.description = _AI_NOTE
    wb.properties.keywords = _AI_KEYWORDS
    wb.properties.category = "AI-generated document"
    # Visible without occupying a cell — a note row would corrupt the data for
    # anyone sorting or summing the sheet.
    ws.oddFooter.left.text = _AI_NOTE
    wb.save(path)


def _write_pptx(content: str, path: str, title: str) -> None:
    from pptx import Presentation
    from pptx.util import Inches, Pt

    prs = Presentation()
    blank, title_layout = prs.slide_layouts[6], prs.slide_layouts[0]

    if title:
        slide = prs.slides.add_slide(title_layout)
        slide.shapes.title.text = _clean(title)
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = _AI_NOTE

    # A heading starts a slide; everything under it becomes that slide's bullets.
    sections: list[tuple[str, list[str]]] = []
    current: tuple[str, list[str]] | None = None
    for raw in content.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue
        if _heading_level(line):
            if current:
                sections.append(current)
            current = (_clean(re.sub(r'^#{1,6}\s+', '', line)), [])
        else:
            text = _clean(re.sub(r'^\s*[-*•]\s+', '', line))
            if current is None:
                current = (_clean(title) or "Overview", [])
            current[1].append(text)
    if current:
        sections.append(current)

    layout = prs.slide_layouts[1]
    for head, bullets in sections:
        slide = prs.slides.add_slide(layout)
        slide.shapes.title.text = head
        body = slide.placeholders[1].text_frame
        body.clear()
        for i, b in enumerate(bullets[:12]):
            para = body.paragraphs[0] if i == 0 else body.add_paragraph()
            para.text = b
        # Visible disclosure on each slide, small and out of the way.
        note = slide.shapes.add_textbox(Inches(0.4), prs.slide_height - Inches(0.45),
                                        Inches(3), Inches(0.3)).text_frame
        note.text = _AI_NOTE
        note.paragraphs[0].runs[0].font.size = Pt(9)

    if not prs.slides:
        slide = prs.slides.add_slide(blank)
        slide.shapes.add_textbox(Inches(1), Inches(1), Inches(8),
                                 Inches(1)).text_frame.text = _clean(content)[:500]

    core = prs.core_properties
    core.author = _AI_CREATOR
    core.comments = _AI_NOTE
    core.keywords = _AI_KEYWORDS
    core.category = "AI-generated document"
    prs.save(path)


_WRITERS = {"docx": _write_docx, "xlsx": _write_xlsx, "pptx": _write_pptx}


def _sanitize_path(path: str, fmt: str, user_id: str = "") -> str:
    return resolve_output_path(path, fmt, user_id)


def _create_sync(content: str, path: str, fmt: str, title: str = "") -> str:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    _WRITERS[fmt](content, str(dest), title)
    kb = round(dest.stat().st_size / 1024, 1)
    return f"{fmt.upper()} created: {dest} ({kb} KB)"


async def handler(content: str, path: str, format: str, title: str = "",
                  _user_id: str = "") -> str:  # noqa: A002
    fmt = (format or "").strip().lower().lstrip(".")
    if fmt not in _WRITERS:
        return (f"Unsupported format {format!r}. Use one of: {', '.join(_FORMATS)} "
                "(or create_pdf for a fixed document).")
    path = _sanitize_path(path, fmt, _user_id)
    loop = asyncio.get_event_loop()
    try:
        return await loop.run_in_executor(None, _create_sync, content, path, fmt, title)
    except ImportError as e:
        return (f"{fmt.upper()} support needs a library that is not installed: {e}. "
                "Install python-docx, openpyxl or python-pptx.")
    except Exception as e:      # noqa: BLE001
        return f"{fmt.upper()} creation failed: {e}"
