"""
Word, Excel and PowerPoint output — the editable formats create_pdf cannot make.

Two properties carry real weight.

**Every file is marked as AI-generated, twice.** `docs/eu-ai-act.md` claims SUNI
marks synthetic output wherever content leaves the system (Art 50(2)), and
`pdf_tool` does it in both the PDF metadata and a visible footer. These are three
new exits. A format that wrote an unmarked file would turn a published
compliance claim into a false one, silently — so each is opened back up and
checked for both the machine-readable property and the visible line.

**A markdown table has to become cells.** A model asked for a table produces
pipes; fed to a CSV reader that comes back as one column of pipe-laden strings —
a spreadsheet that looks generated and cannot be sorted or summed.
"""
from __future__ import annotations

import asyncio
import zipfile
from pathlib import Path

import pytest

from suni.tools import document_tool as dt

MARK = "AI-generated by SUNI"


def _run(**kw) -> str:
    return asyncio.run(dt.handler(**kw))


# ── the three formats actually produce openable files ────────────────────────
@pytest.mark.parametrize("fmt", ["docx", "xlsx", "pptx"])
def test_it_writes_a_real_openable_file(tmp_path, fmt):
    out = tmp_path / f"report.{fmt}"
    msg = _run(content="# Heading\n- one\n- two", path=str(out),
               format=fmt, title="Quarterly")
    assert out.exists(), msg
    assert fmt.upper() in msg and "created" in msg
    # every Office format is a zip container; a corrupt write fails here
    assert zipfile.is_zipfile(out), f"{fmt} is not a valid Office package"


@pytest.mark.parametrize("fmt", ["docx", "xlsx", "pptx"])
def test_every_format_is_marked_ai_generated(tmp_path, fmt):
    """Machine-readable marking, per Art 50(2)."""
    out = tmp_path / f"m.{fmt}"
    _run(content="| a | b |\n|---|---|\n| 1 | 2 |", path=str(out),
         format=fmt, title="T")
    blob = b""
    with zipfile.ZipFile(out) as z:
        for name in z.namelist():
            if "core.xml" in name or "app.xml" in name or "docProps" in name:
                blob += z.read(name)
    text = blob.decode("utf-8", "replace")
    assert "EU-AI-Act-Art-50" in text or MARK in text, \
        f"{fmt} carries no machine-readable AI marking"


@pytest.mark.parametrize("fmt", ["docx", "xlsx", "pptx"])
def test_every_format_is_visibly_marked(tmp_path, fmt):
    """A human opening the file must be able to see it too."""
    out = tmp_path / f"v.{fmt}"
    _run(content="# S\n- x", path=str(out), format=fmt, title="T")
    found = False
    with zipfile.ZipFile(out) as z:
        for name in z.namelist():
            if name.endswith(".xml"):
                if MARK in z.read(name).decode("utf-8", "replace"):
                    found = True
                    break
    assert found, f"{fmt} has no visible '{MARK}' disclosure"


# ── the spreadsheet actually gets cells ──────────────────────────────────────
def test_a_markdown_table_becomes_cells_not_one_pipe_column(tmp_path):
    out = tmp_path / "t.xlsx"
    _run(content="| Name | Qty |\n|------|-----|\n| Bolts | 12 |\n| Nuts | 7 |",
         path=str(out), format="xlsx")
    from openpyxl import load_workbook
    ws = load_workbook(out).active
    rows = [[c.value for c in r] for r in ws.iter_rows()]
    assert rows[0] == ["Name", "Qty"], f"header not split into cells: {rows[0]}"
    assert ["Bolts", "12"] in rows or ["Bolts", 12] in rows
    assert len(rows) == 3, "the |---| separator row became data"
    for row in rows:
        assert not any("|" in str(c) for c in row if c is not None)


def test_csv_content_also_becomes_cells(tmp_path):
    out = tmp_path / "c.xlsx"
    _run(content="a,b,c\n1,2,3", path=str(out), format="xlsx")
    from openpyxl import load_workbook
    rows = [[c.value for c in r] for r in load_workbook(out).active.iter_rows()]
    assert rows[0] == ["a", "b", "c"]


def test_tab_separated_content_is_detected(tmp_path):
    out = tmp_path / "t2.xlsx"
    _run(content="a\tb\n1\t2", path=str(out), format="xlsx")
    from openpyxl import load_workbook
    rows = [[c.value for c in r] for r in load_workbook(out).active.iter_rows()]
    assert rows[0] == ["a", "b"]


# ── docx / pptx structure ────────────────────────────────────────────────────
def test_docx_keeps_headings_and_bullets(tmp_path):
    out = tmp_path / "d.docx"
    _run(content="# Big\nSome prose.\n- first\n- second\n1. numbered",
         path=str(out), format="docx", title="Doc")
    from docx import Document
    doc = Document(out)
    styles = [p.style.name for p in doc.paragraphs]
    texts = [p.text for p in doc.paragraphs]
    assert any("Heading" in s for s in styles)
    assert "List Bullet" in styles and "List Number" in styles
    assert "first" in texts and "Some prose." in texts


def test_markdown_emphasis_does_not_survive_literally(tmp_path):
    out = tmp_path / "e.docx"
    _run(content="This is **bold** and `code` and [a link](http://x.y)",
         path=str(out), format="docx")
    from docx import Document
    text = "\n".join(p.text for p in Document(out).paragraphs)
    assert "**" not in text and "`" not in text and "](" not in text
    assert "bold" in text and "a link" in text


def test_pptx_makes_one_slide_per_heading(tmp_path):
    out = tmp_path / "p.pptx"
    _run(content="# One\n- a\n# Two\n- b", path=str(out), format="pptx", title="Deck")
    from pptx import Presentation
    prs = Presentation(out)
    titles = [s.shapes.title.text for s in prs.slides if s.shapes.title]
    assert "One" in titles and "Two" in titles
    assert len(prs.slides) >= 3, "title slide + one per heading"


# ── failure modes ────────────────────────────────────────────────────────────
def test_an_unknown_format_is_refused_clearly(tmp_path):
    msg = _run(content="x", path=str(tmp_path / "f.odt"), format="odt")
    assert "Unsupported" in msg and "docx" in msg
    assert not list(tmp_path.iterdir()), "a file was written for a bad format"


def test_the_extension_follows_the_format(tmp_path):
    """A model that passes report.pdf with format=xlsx must not produce a file
    that lies about what it is."""
    _run(content="a,b", path=str(tmp_path / "report.pdf"), format="xlsx")
    assert (tmp_path / "report.xlsx").exists()
    assert not (tmp_path / "report.pdf").exists()


def test_illegal_filename_characters_are_stripped(tmp_path):
    """Built as a string, not via `tmp_path / name`: on Windows a colon in the
    name is read as a drive separator, so Path() would discard the directory
    before the tool ever saw the value. A model passes a whole path string."""
    msg = _run(content="x", path=f"{tmp_path}/a:b?c.docx", format="docx")
    assert "created" in msg, msg
    written = list(tmp_path.glob("*.docx"))
    assert written, "nothing was written"
    assert not any(ch in written[0].name for ch in ':?<>|*"'), written[0].name


def test_a_directory_in_the_path_is_never_mistaken_for_a_filename(tmp_path):
    """The sanitiser splits on the separator itself; it must not mangle the
    parent directory, only the final component."""
    sub = tmp_path / "Reports 2026"
    sub.mkdir()
    msg = _run(content="x", path=f"{sub}/summary.docx", format="docx")
    assert (sub / "summary.docx").exists(), msg


def test_missing_directories_are_created(tmp_path):
    out = tmp_path / "deep" / "nested" / "r.docx"
    _run(content="x", path=str(out), format="docx")
    assert out.exists()


def test_empty_content_does_not_crash(tmp_path):
    for fmt in ("docx", "xlsx", "pptx"):
        msg = _run(content="", path=str(tmp_path / f"empty.{fmt}"), format=fmt)
        assert "created" in msg, msg


# ── registered in BOTH places ────────────────────────────────────────────────
def test_the_tool_is_registered_in_the_server_and_the_cli():
    """A tool registered in one and not the other is a recipe that works in
    testing and is missing in production — network_tool and memory_tool shipped
    that way for months."""
    root = Path(__file__).resolve().parent.parent
    for rel, enc in (("suni/main.py", "utf-8"), ("suni/web/server.py", "utf-8-sig")):
        src = (root / rel).read_text(encoding=enc)
        assert "document_tool" in src, f"{rel} does not import document_tool"
        assert "registry.register(document_tool.SCHEMA" in src, \
            f"{rel} imports document_tool but never registers it"


def test_one_tool_not_three():
    """Every schema is sent on every request; for an admin the tool payload is
    already over half of an 8192 context. Three format-specific tools would cost
    roughly three times as much, forever."""
    import json
    assert dt.SCHEMA["name"] == "create_document"
    assert set(dt.SCHEMA["parameters"]["properties"]["format"]["enum"]) == \
        {"docx", "xlsx", "pptx"}
    assert len(json.dumps(dt.SCHEMA)) // 4 < 220, "the schema itself has grown too fat"


# ── the shared path helper ───────────────────────────────────────────────────
def test_pdf_and_document_share_one_path_sanitiser():
    """Both had to solve the same Windows drive-separator problem. One copy
    means the next fix lands in one place rather than half of them."""
    import inspect
    from suni.tools import pdf_tool
    from suni.tools.safe_path import safe_output_path
    assert "safe_output_path" in inspect.getsource(pdf_tool._sanitize_path)
    assert "safe_output_path" in inspect.getsource(dt._sanitize_path)
    assert callable(safe_output_path)


def test_pdf_no_longer_breaks_on_a_colon_in_the_filename(tmp_path):
    """The bug this shared helper exists for: Path() reads the colon as a drive
    separator, so the parent resolved to 'a:' and the write failed outright."""
    from suni.tools.pdf_tool import _sanitize_path
    out = _sanitize_path(f"{tmp_path}/quarterly:report?.pdf")
    assert ":" not in Path(out).name and "?" not in Path(out).name
    assert out.endswith(".pdf")
    assert str(tmp_path) in out, "the directory was discarded"


def test_the_pdf_extension_is_still_forced():
    from suni.tools.pdf_tool import _sanitize_path
    assert _sanitize_path("C:/out/notes.txt").endswith(".pdf")
