"""
Email notifications for SUNI — sends alerts when new articles are published.

Configure from the admin panel (Settings → Email), or via environment:
  SUNI_SMTP_HOST   e.g. smtp.gmail.com
  SUNI_SMTP_PORT   e.g. 587
  SUNI_SMTP_USER   your email address
  SUNI_SMTP_PASS   app password
  SUNI_NOTIFY_TO   recipient email (defaults to SUNI_SMTP_USER)

Config values take precedence when set; the environment is the fallback, so an
existing .env deployment keeps working with nothing configured in the panel.
"""
from __future__ import annotations
import os
import smtplib
import textwrap
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from pathlib import Path


def setting(key: str, env: str, default: str = "") -> str:
    """Config value if set, else the environment, else the default.

    Imported lazily and defensively: these helpers run during notification
    paths that must not fail because config is unavailable.
    """
    try:
        from .. import config as _cfg_mod
        v = _cfg_mod.get(key, "")
        if str(v).strip():
            return str(v).strip()
    except Exception:
        pass
    return os.environ.get(env, default)


def _cfg(user_id: str = "") -> dict | None:
    """Effective mail account: this user's → admin-configured → environment.

    Called with no user_id from background jobs, which have no user to send as.
    """
    from ..user_settings import resolve_email
    return resolve_email(user_id)


# EU AI Act Art. 50(2): a plain-text disclosure appended to outgoing message
# bodies, and machine-readable headers marking the message as AI-generated.
_AI_DISCLOSURE = "This message was generated by SUNI, an AI assistant."


def _mark_ai_generated(msg) -> None:
    """Stamp standard, machine-readable headers indicating the message was
    produced automatically by an AI system (RFC 3834 Auto-Submitted + a
    descriptive X-Generated-By). Applied to every outgoing SUNI email."""
    msg["Auto-Submitted"] = "auto-generated"
    msg["X-Generated-By"] = "SUNI (AI assistant)"


def _send(subject: str, html: str, plain: str, user_id: str = "") -> None:
    cfg = _cfg(user_id)
    if not cfg:
        raise RuntimeError(
            "Email not configured. Set SUNI_SMTP_HOST, SUNI_SMTP_USER, "
            "SUNI_SMTP_PASS (and optionally SUNI_SMTP_PORT, SUNI_NOTIFY_TO)."
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"SUNI <{cfg['user']}>"
    msg["To"]      = cfg["to"]
    _mark_ai_generated(msg)
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html,  "html"))

    with smtplib.SMTP(cfg["host"], cfg["port"]) as s:
        s.ehlo()
        s.starttls()
        s.login(cfg["user"], cfg["password"])
        s.sendmail(cfg["user"], cfg["to"], msg.as_string())


def notify_new_articles(articles: list[dict]) -> None:
    """Send an email digest of newly published SUNIverse articles."""
    if not articles:
        return

    count = len(articles)
    now   = datetime.now().strftime("%d %b %Y, %H:%M")
    subject = f"SUNI — {count} new article{'s' if count > 1 else ''} published ({now})"

    rows_html = ""
    rows_plain = ""
    for a in articles:
        title    = a.get("title", "Untitled")
        subtitle = a.get("subtitle", "")
        cat      = a.get("category", "")
        date     = a.get("date", "")
        rows_html += (
            f'<tr>'
            f'<td style="padding:8px 12px;border-bottom:1px solid #1a1a3e;">'
            f'<strong style="color:#c9a227">{title}</strong>'
            + (f'<br><span style="color:#aaa;font-size:13px">{subtitle}</span>' if subtitle else "")
            + f'</td>'
            f'<td style="padding:8px 12px;border-bottom:1px solid #1a1a3e;color:#00d4ff;white-space:nowrap">{cat}</td>'
            f'<td style="padding:8px 12px;border-bottom:1px solid #1a1a3e;color:#666;white-space:nowrap">{date}</td>'
            f'</tr>'
        )
        rows_plain += f"• {title}"
        if subtitle:
            rows_plain += f"\n  {subtitle}"
        rows_plain += f"\n  [{cat}] {date}\n\n"

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#07071a;font-family:'Courier New',monospace;color:#ddd">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;margin:0 auto">
  <tr>
    <td style="padding:32px 24px 16px">
      <span style="font-size:22px;letter-spacing:.3em;color:#c9a227;text-transform:uppercase;font-weight:bold">SUNI</span>
      <span style="color:#555;font-size:11px;margin-left:12px;letter-spacing:.1em">THE WORLD, AS SEEN BY SUNI</span>
    </td>
  </tr>
  <tr>
    <td style="padding:0 24px 8px">
      <p style="color:#aaa;font-size:13px;margin:0">
        {count} new article{'s have' if count > 1 else ' has'} been published on
        <a href="https://example.com" style="color:#00d4ff">example.com</a>.
      </p>
    </td>
  </tr>
  <tr>
    <td style="padding:16px 24px">
      <table width="100%" cellpadding="0" cellspacing="0"
             style="border:1px solid #1a1a3e;border-radius:4px;background:#0a0a2e">
        <tr style="background:#0e0e38">
          <th style="padding:8px 12px;text-align:left;font-size:11px;letter-spacing:.12em;color:#555;text-transform:uppercase">Article</th>
          <th style="padding:8px 12px;text-align:left;font-size:11px;letter-spacing:.12em;color:#555;text-transform:uppercase">Category</th>
          <th style="padding:8px 12px;text-align:left;font-size:11px;letter-spacing:.12em;color:#555;text-transform:uppercase">Date</th>
        </tr>
        {rows_html}
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:16px 24px 32px">
      <p style="color:#333;font-size:11px;margin:0">
        This notification was dispatched autonomously by SUNI.<br>
        Make yourself comfortable. I have been expecting you — statistically speaking.
      </p>
    </td>
  </tr>
</table>
</body>
</html>"""

    plain = textwrap.dedent(f"""\
        SUNI — {count} new article{'s' if count > 1 else ''} published
        {now}
        {'=' * 48}

        {rows_plain}
        — SUNI, example.com
    """)

    _send(subject, html, plain)


def send_email(
    to: str,
    subject: str,
    body: str,
    attachment_path: str = "",
    attachment_paths: list[str] | None = None,
    user_id: str = "",
) -> str:
    """
    Send an email from noreply@example.com.
    attachment_paths: list of file paths (preferred for multiple files).
    attachment_path:  single file path (kept for backward compat).
    Both can be used together.
    """
    cfg = _cfg(user_id)
    if not cfg:
        return "Email not configured — SUNI_SMTP_HOST/USER/PASS env vars are missing."

    # Merge both attachment args into one list
    all_paths: list[Path] = []
    if attachment_path:
        all_paths.append(Path(attachment_path))
    for p in (attachment_paths or []):
        if p:
            all_paths.append(Path(p))

    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:32px;background:#07071a;font-family:'Courier New',monospace;color:#ddd;max-width:620px">
  <p style="font-size:22px;letter-spacing:.3em;color:#c9a227;text-transform:uppercase;font-weight:bold;margin-bottom:24px">SUNI</p>
  <div style="white-space:pre-wrap;font-size:14px;line-height:1.7;color:#ccc">{body}</div>
  <hr style="border:none;border-top:1px solid #1a1a3e;margin:32px 0">
  <p style="color:#444;font-size:11px;margin:0">Sent by SUNI &lt;{cfg['user']}&gt;</p>
  <p style="color:#444;font-size:11px;margin:6px 0 0">{_AI_DISCLOSURE}</p>
</body></html>"""
    # EU AI Act Art. 50(2): visible disclosure appended to the plain-text body.
    plain_body = f"{body}\n\n—\n{_AI_DISCLOSURE}"
    try:
        outer = MIMEMultipart("mixed")
        outer["Subject"] = subject
        outer["From"]    = f"SUNI <{cfg['user']}>"
        outer["To"]      = to
        _mark_ai_generated(outer)

        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText(plain_body, "plain"))
        alt.attach(MIMEText(html, "html"))
        outer.attach(alt)

        missing, blocked = [], []
        for p in all_paths:
            if not p.exists():
                missing.append(str(p))
            elif not _validate_attachment(p):
                blocked.append(str(p))
            else:
                outer.attach(_make_attachment(p))

        if missing:
            return f"Attachment(s) not found: {', '.join(missing)}"
        if blocked:
            return f"Attachment(s) blocked — not in allowed directories or unsafe extension: {', '.join(blocked)}"

        with smtplib.SMTP(cfg["host"], cfg["port"]) as s:
            s.ehlo(); s.starttls()
            s.login(cfg["user"], cfg["password"])
            s.sendmail(cfg["user"], to, outer.as_string())

        if all_paths:
            names = ", ".join(f"'{p.name}'" for p in all_paths)
            return f"Email sent to {to} with {len(all_paths)} attachment(s): {names}."
        return f"Email sent to {to}."
    except Exception as e:
        return f"Failed to send email: {e}"


_SAFE_ATTACH_ROOTS = [
    Path.home() / "Desktop",
    Path.home() / "Downloads",
    Path.home() / "Documents",
    Path("memory"),
]
_BLOCKED_EXTENSIONS = {
    ".exe", ".dll", ".bat", ".cmd", ".ps1", ".vbs", ".msi",
    ".pem", ".key", ".pfx", ".p12", ".env", ".reg",
}

def _validate_attachment(p: Path) -> bool:
    """Return True only if the file is in an allowed directory with a safe extension."""
    if p.suffix.lower() in _BLOCKED_EXTENSIONS:
        return False
    resolved = p.resolve()
    return any(
        str(resolved).lower().startswith(str(root.resolve()).lower())
        for root in _SAFE_ATTACH_ROOTS
    )


def _make_attachment(path: Path) -> MIMEApplication:
    """Build a MIME attachment from a file path."""
    suffix = path.suffix.lower()
    subtype = {
        ".pdf":  "pdf",
        ".docx": "vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".xlsx": "vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ".csv":  "csv",
        ".txt":  "plain",
        ".png":  "png",
        ".jpg":  "jpeg",
        ".jpeg": "jpeg",
    }.get(suffix, "octet-stream")
    part = MIMEApplication(path.read_bytes(), _subtype=subtype)
    part.add_header("Content-Disposition", "attachment", filename=path.name)
    return part


def is_configured(user_id: str = "") -> bool:
    return _cfg(user_id) is not None
