"""
Curated MCP server catalog for SUNI.

Each entry has the information needed to configure an MCP server.
Admin can add any entry to memory/mcp_servers.json with one click.

Package notes:
- Official active:   @modelcontextprotocol/server-* (filesystem, fetch, memory, time, sequentialthinking)
- Official archived: some packages moved to modelcontextprotocol/servers-archived in May 2025
                     (brave-search, slack, postgres, sqlite, gdrive, puppeteer) — verify npm
                     package names before installing; command syntax below is current best-known.
- Tool count matters: Playwright alone is ~25 tools; adding many servers increases prompt overhead.
"""
from __future__ import annotations

CATALOG: list[dict] = [
    {
        "id":               "playwright",
        "name":             "Playwright",
        "category":         "Browser",
        "description":      "Real-browser automation — navigate, click, fill forms, take screenshots, scrape JS-heavy pages. ~25 tools.",
        "command":          "npx",
        "args":             ["@playwright/mcp@latest", "--headless"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Already configured in Claude Desktop config. Add here if you want SUNI-specific config or non-headless mode.",
    },
    {
        "id":               "filesystem",
        "name":             "Filesystem",
        "category":         "Files",
        "description":      "Read, write, search and move files in configured directories. Safe access controls.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-filesystem", "<directory-to-expose>"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Replace path with the root directory to expose. Multiple paths can be added as extra args.",
    },
    {
        "id":               "fetch",
        "name":             "Fetch",
        "category":         "Web",
        "description":      "HTTP fetch with automatic HTML→Markdown conversion — read web pages cleanly.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-fetch"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "",
    },
    {
        "id":               "memory",
        "name":             "Knowledge Graph Memory",
        "category":         "Memory",
        "description":      "Persistent cross-session structured memory via knowledge graph — store entities and relationships.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-memory"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Complements SUNI's built-in vector memory. Useful for structured fact storage.",
    },
    {
        "id":               "time",
        "name":             "Time",
        "category":         "Utility",
        "description":      "Timezone-aware date/time operations — convert between zones, parse natural-language dates.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-time"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "",
    },
    {
        "id":               "sequential-thinking",
        "name":             "Sequential Thinking",
        "category":         "Reasoning",
        "description":      "Externalizes chain-of-thought as revisable planning steps — improves complex multi-step reasoning.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-sequentialthinking"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Can significantly increase token usage. Best for complex reasoning tasks.",
    },
    {
        "id":               "git",
        "name":             "Git",
        "category":         "Development",
        "description":      "Git operations on local repositories — log, diff, blame, status, commit history.",
        "command":          "uvx",
        "args":             ["mcp-server-git", "--repository", "<path to your repository>"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Requires uvx (Python). Replace repository path. Install uvx: pip install uv.",
    },
    {
        "id":               "brave-search",
        "name":             "Brave Search",
        "category":         "Search",
        "description":      "Privacy-first web search using Brave's independent index. Free tier: 2,000 queries/month.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-brave-search"],
        "env":              {"BRAVE_API_KEY": "YOUR_BRAVE_API_KEY"},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Get free API key at brave.com/search/api/. Package may be in archived repo — verify.",
    },
    {
        "id":               "notion",
        "name":             "Notion",
        "category":         "Productivity",
        "description":      "Access Notion workspace — search pages, read/write databases, create and update content.",
        "command":          "npx",
        "args":             ["-y", "@notionhq/notion-mcp-server"],
        "env":              {"OPENAPI_MCP_HEADERS": "{\"Authorization\": \"Bearer ntn_YOUR_TOKEN\", \"Notion-Version\": \"2022-06-28\"}"},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Create an integration at notion.so/my-integrations and copy the Internal Integration Token.",
    },
    {
        "id":               "sqlite",
        "name":             "SQLite",
        "category":         "Database",
        "description":      "Query and analyse SQLite databases. Business intelligence and data exploration.",
        "command":          "uvx",
        "args":             ["mcp-server-sqlite", "--db-path", "<path to your .db file>"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Requires uvx. Replace db-path with your .db file. Package may be in archived repo.",
    },
    {
        "id":               "postgres",
        "name":             "PostgreSQL",
        "category":         "Database",
        "description":      "Read-only SQL access to PostgreSQL with schema inspection and query capabilities.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-postgres", "postgresql://localhost/mydb"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Replace connection string. Package may be in archived repo — verify npm name.",
    },
    {
        "id":               "github",
        "name":             "GitHub",
        "category":         "Development",
        "description":      "Official GitHub MCP — issues, PRs, code search, repository operations. 15k+ stars.",
        "command":          "docker",
        "args":             ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server"],
        "env":              {"GITHUB_PERSONAL_ACCESS_TOKEN": "ghp_YOUR_PAT"},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Requires Docker. Create a PAT at github.com/settings/tokens with repo scope.",
    },
    {
        "id":               "slack",
        "name":             "Slack",
        "category":         "Communication",
        "description":      "Read Slack channels, search messages, post to channels — without installing a workspace bot.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-slack"],
        "env":              {"SLACK_BOT_TOKEN": "xoxb-...", "SLACK_TEAM_ID": "T..."},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Create Slack app at api.slack.com/apps with channels:read, chat:write scopes.",
    },
    {
        "id":               "sentry",
        "name":             "Sentry",
        "category":         "Development",
        "description":      "Query Sentry error tracking — issues, events, performance data.",
        "command":          "npx",
        "args":             ["-y", "@sentry/mcp-server@latest"],
        "env":              {},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Authenticated interactively on first use — will prompt for org and auth token.",
    },
    {
        "id":               "exa",
        "name":             "Exa Search",
        "category":         "Search",
        "description":      "Semantic web search with neural embeddings — finds conceptually relevant content. 1,000 free/month.",
        "command":          "npx",
        "args":             ["-y", "exa-mcp-server"],
        "env":              {"EXA_API_KEY": "YOUR_EXA_API_KEY"},
        "requires_api_key": True,
        "official":         False,
        "notes":            "Get API key at exa.ai. Excellent for research-style queries.",
    },
    {
        "id":               "google-drive",
        "name":             "Google Drive",
        "category":         "Productivity",
        "description":      "Search and read Google Drive files with automatic format conversion (Docs→Markdown etc.).",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-gdrive"],
        "env":              {},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Requires OAuth setup — follow modelcontextprotocol.io/docs/servers/gdrive.",
    },
    {
        "id":               "puppeteer",
        "name":             "Puppeteer",
        "category":         "Browser",
        "description":      "Browser automation via Puppeteer — screenshots, PDF, web scraping. Alternative to Playwright.",
        "command":          "npx",
        "args":             ["-y", "@modelcontextprotocol/server-puppeteer"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Choose Playwright OR Puppeteer — not both. Package may be in archived repo.",
    },
    {
        "id":               "supabase",
        "name":             "Supabase",
        "category":         "Database",
        "description":      "Manage Supabase projects — databases, auth, storage, edge functions, schema migrations.",
        "command":          "npx",
        "args":             ["-y", "@supabase/mcp-server-supabase@latest", "--access-token", "sbp_YOUR_TOKEN"],
        "env":              {},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Get personal access token from supabase.com/dashboard/account/tokens.",
    },
    {
        "id":               "linear",
        "name":             "Linear",
        "category":         "Productivity",
        "description":      "Issue tracking and project management — tickets, cycles, sprints, team workflows.",
        "command":          "npx",
        "args":             ["-y", "linear-mcp-server"],
        "env":              {"LINEAR_API_KEY": "lin_api_YOUR_KEY"},
        "requires_api_key": True,
        "official":         False,
        "notes":            "Get API key from linear.app/settings/api.",
    },
    {
        "id":               "firecrawl",
        "name":             "Firecrawl",
        "category":         "Web",
        "description":      "Advanced web scraping — handles JS-heavy pages, structured extraction, site crawling.",
        "command":          "npx",
        "args":             ["-y", "firecrawl-mcp"],
        "env":              {"FIRECRAWL_API_KEY": "fc-YOUR_KEY"},
        "requires_api_key": True,
        "official":         False,
        "notes":            "Get API key at firecrawl.dev. Generous free tier.",
    },
    {
        "id":               "context7",
        "name":             "Context7",
        "category":         "Development",
        "description":      "Up-to-date, version-accurate documentation for thousands of libraries/frameworks, injected on demand. A high-value first install for coding tasks.",
        "command":          "npx",
        "args":             ["-y", "@upstash/context7-mcp"],
        "env":              {},
        "requires_api_key": False,
        "official":         True,
        "notes":            "Works key-free; an optional CONTEXT7_API_KEY raises rate limits (context7.com).",
    },
    {
        "id":               "stripe",
        "name":             "Stripe",
        "category":         "Payments",
        "description":      "Query and manage Stripe — customers, invoices, payments, products, subscriptions.",
        "command":          "npx",
        "args":             ["-y", "@stripe/mcp", "--tools=all"],
        "env":              {"STRIPE_SECRET_KEY": "sk_test_YOUR_KEY"},
        "requires_api_key": True,
        "official":         True,
        "notes":            "Use a restricted/test key. Docs at docs.stripe.com/mcp.",
    },
]

CATEGORIES = sorted({s["category"] for s in CATALOG})


def get_by_id(server_id: str) -> dict | None:
    return next((s for s in CATALOG if s["id"] == server_id), None)


def get_by_category(category: str) -> list[dict]:
    return [s for s in CATALOG if s["category"] == category]
